#!/bin/sh
set -eu
cd "$(dirname "$0")"
export CARGO_NET_OFFLINE=true
export RUSTFLAGS="-L native=/adapter -C link-arg=-Wl,-rpath,/adapter${RUSTFLAGS:+ $RUSTFLAGS}"
cargo build --offline --locked --release
cp target/release/service service
chmod +x service
