"""Prepare one package for holdout, without publishing it before confirmation."""
import argparse,shutil,re
from common import *
from variants import replace_fn

def main():
 p=argparse.ArgumentParser();p.add_argument('winner');a=p.parse_args();dest=WORK/'candidate'
 if dest.exists():raise SystemExit('candidate already prepared; holdout must not be retuned')
 shutil.copytree(WORK/a.winner,dest,ignore=shutil.ignore_patterns('.zig-cache','zig-out'))
 if a.winner=='baseline':
  save(WORK/'candidate-preparation.json',dict(winner='baseline',source_digest=source_digest(dest),winner_digest=source_digest(FROZEN),changes='none; baseline selected'))
  return
 s=(dest/'src/root.zig').read_text()
 old=(FROZEN/'src/root.zig').read_text().split('\ntest {')[0].replace('fn inverse(','pub fn inverse(').replace('fn recode(','pub fn recode(')
 (dest/'src/test_residual_baseline.zig').write_text(old)
 if 'fn splitScalar' in s:
  s=replace_fn(s,'recode','');s=replace_fn(s,'recodeWidth','');s=s.replace('const Digits = struct { values: [257]i8 = @splat(0), len: usize = 0 };','')
  s=s.replace('const digits = recode(scalar);','const digits = @import("test_residual_baseline.zig").recode(scalar);')
 if 'fn sqrtPower' in s:s=replace_fn(s,'pow','')
 s=s.replace('Constants are generated by derive.py','Constants are generated by tools/derive_constants.py')
 s=s.replace('// Coefficients stay below the odd modulus; x+modulus fits u257, and its\n// half fits u256. Inputs are public and the iteration count is variable.','// Coefficients remain below the odd modulus. The odd half is formed from\n// two shifted values plus one, with sum below the modulus. Inputs are public.')
 (dest/'src/root.zig').write_text(s)
 # The standalone regeneration tool uses only Python integers and curve equations.
 tools=dest/'tools';tools.mkdir(exist_ok=True)
 derive=(HERE/'derive.py').read_text();derive=derive.replace('from common import *','from pathlib import Path\nWORK=Path(__file__).resolve().parent\ndef save(path,obj): pass')
 derive=derive[:derive.index("if __name__=='__main__':")]+'''if __name__=='__main__':
 beta,lam,a,b=derive()
 text=(Path(__file__).resolve().parents[1]/'src/root.zig').read_text()
 import re
 for name,value in [('beta',beta),('lambda',lam)]:
  found=re.search(r'const '+name+r': u256 = (0x[0-9a-f]+);',text)
  assert found and int(found[1],16)==value,name
 for name,values in [('basis_a',a),('basis_b',b)]:
  found=re.search(r'const '+name+r': \\[2\\]i512 = \\.\\{ ([^}]+) \\};',text)
  assert found and tuple(map(int,found[1].split(',')))==values,name
 print(json.dumps({'beta':hex(beta),'lambda':hex(lam),'basis':[a,b],'symbolic_sqrt_verified':bool(sqrt_source('chain')),'result':'passed'}))
'''
 (tools/'derive_constants.py').write_text(derive)
 zon=dest/'build.zig.zon';z=zon.read_text();z=z.replace('"DERIVATIONS.md"','"DERIVATIONS.md", "tools"');zon.write_text(z)
 readme=(dest/'README.md').read_text().replace('Verification uses separate-base width-5 signed digits and a generated\nimmutable generator table.','Verification uses independently derived GLV splits and separate-base signed\ndigits, with generated immutable generator and endomorphism tables.')
 readme+='\nRegenerate and verify optimization constants with `python3 tools/derive_constants.py`.\nThis optional development tool uses only Python standard-library integer arithmetic;\nit is not a build or production dependency. All inversion and recoding operate\non public inputs and remain variable-time.\n'
 (dest/'README.md').write_text(readme)
 deriv=(dest/'DERIVATIONS.md').read_text()
 deriv=deriv.replace('Square roots retain exponentiation by (p+1)/4; scalar products retain widened\ninteger reduction. No custom limb arithmetic is claimed.','For odd x,m, (x+m)/2 = (x>>1)+(m>>1)+1. Because x<m, the result\nis below m and every positive partial sum fits u256. No custom limb arithmetic\nis used in the retained field implementation.')
 deriv=deriv[:deriv.index('## Signed digits and tables')]+'''## Independently generated decompression and scalar reduction

The square-root exponent is (p+1)/4 = 2^254 - 2^30 - 244. The development
generator constructs powers a^(2^k-1) by concatenating runs of one bits:
M(2k)=M(k)^(2^k) M(k), and M(k+1)=M(k)^2 a. It symbolically tracks each
exponent and reconstructs the exact target before emitting the schedule.
Verification still checks y^2=rhs and selects the requested parity.

For scalar products write n=2^256-c, with c computed from n rather than
transcribed. Replacing a high half H by Hc preserves the residue. Three folds
of any 512-bit input yield less than 2n; the third result may still have 257
bits. Conditional subtraction precedes narrowing. A 256-bit digest requires
only one conditional subtraction. Public scalar acceptance remains x<n.

## GLV lattice and signed multiplication

The mathematical source is Gallant, Lambert, Vanstone,
[Faster Point Multiplication on Elliptic Curves with Efficient Endomorphisms](https://www.iacr.org/archive/crypto2001/21390189.pdf),
especially its prime-field cube-root endomorphism and lattice decomposition.
HMV supplies the signed-digit and simultaneous-multiplication background;
EFD supplies the coordinate equations. No C implementation material is used.

`tools/derive_constants.py` enumerates small integer bases to obtain nontrivial
cube roots modulo p and n. It pairs them by checking phi(G)=lambda G using
independent affine equations. Exact Gauss reduction starts at (n,0),(-lambda,1),
with nearest-integer ties away from zero. The basis determinant is n and each
basis vector lies in the kernel x+lambda y=0 mod n.

For basis vectors a,b, round the coordinates of (k,0) in that basis and subtract
the resulting lattice vector. Each rounding error has magnitude at most 1/2,
so each residual coordinate is bounded by (abs(a_i)+abs(b_i))/2. The generator
checks these exact bounds are below 2^129; sampled splits are additional tests,
not the bound proof. Signed intermediates fit i512 and residuals fit i256.

Four separate streams represent G,phi(G),P,phi(P). The variable table is built
and normalized once, then transformed by x -> beta*x. Compile-time generator
tables are calculated from package arithmetic. Streams use 131 digit slots to
cover the proven signed bound and carry. Every nonzero width-w digit is odd
and lies between -(2^(w-1)-1) and +(2^(w-1)-1). Each simultaneous nonzero digit
performs its own mixed addition; there is no joint matrix or shared-Z table.

Tweaks multiply the generator with its two GLV streams and mixed-add the affine
key exactly once. Zero tweaks and infinity preserve their documented behavior.
Old binary/Fermat and first-campaign routines live in test comparators, with no
runtime dispatch or fallback. Runtime safety remains enabled throughout.
'''
 (dest/'DERIVATIONS.md').write_text(deriv)
 run(['zig','fmt',dest/'src/root.zig',dest/'src/test_residual_baseline.zig',zon])
 run([sys.executable,tools/'derive_constants.py'])
 save(WORK/'candidate-preparation.json',dict(winner=a.winner,source_digest=source_digest(dest),winner_digest=source_digest(WORK/a.winner),changes='formatting, test-only comparator extraction, standalone derivation generator, documentation'))
 print(source_digest(dest))
if __name__=='__main__':main()
