// AUTO-GENERATED from pybitnode/wire/capabilities.py — do not edit by hand
#include "cpbitnode/wire/capabilities.hpp"

namespace cpbitnode::wire {
extern const std::vector<WireCheckpoint> kCheckpoints = {
    {"cp0_framing", "Message framing", "Binary container format: magic, command, length, checksum.", "phase0"},
    {"cp1_handshake", "Connection handshake", "version/verack exchange with correct services and user agent.", "phase0"},
    {"cp2_discovery", "Peer discovery", "Find and connect to testnet4 peers.", "phase0"},
    {"cp3_headers", "Header sync", "Download, parse, and persist the header chain.", "phase1"},
    {"cp4_blocks", "Block download", "Request and receive full blocks over the wire.", "phase2"},
    {"cp5_tx_relay", "Transaction relay", "Receive, validate policy, and rebroadcast transactions.", "phase4"},
    {"cp6_serving", "Inbound serving", "Respond to peer requests as a network participant.", "phase4"},
    {"cp7_keepalive", "Connection keepalive", "ping/pong and connection health.", "phase0"},
    {"cp8_extensions", "Protocol extensions", "Optional modern protocol messages (sendheaders, compact blocks, etc.).", "phase5"},
};
extern const std::vector<WireCapability> kCapabilities = {
    {"frame.build", "cp0_framing", "framing", "Build P2P message frame", "Serialize 24-byte header + payload with correct checksum.", true, true},
    {"frame.parse", "cp0_framing", "framing", "Parse P2P message header", "Read magic, command, length, checksum from 24-byte header.", true, true},
    {"frame.checksum", "cp0_framing", "framing", "Verify payload checksum", "Reject messages where checksum != first 4 bytes of double-SHA256(payload).", true, true},
    {"frame.magic", "cp0_framing", "framing", "Network magic validation", "Reject messages with wrong chain magic bytes.", true, true},
    {"transport.outbound", "cp0_framing", "transport", "Outbound TCP connection", "Connect to peer host:port over asyncio TCP.", true, true},
    {"transport.inbound", "cp0_framing", "transport", "Inbound TCP listener", "Accept incoming P2P connections on chain port.", false, false},
    {"handshake.version.send", "cp1_handshake", "handshake", "Send version", "Send version message with protocol version, services, addrs, nonce, user agent.", true, true},
    {"handshake.version.recv", "cp1_handshake", "handshake", "Receive and parse version", "Deserialize peer version including start_height and relay flag.", true, true},
    {"handshake.verack.send", "cp1_handshake", "handshake", "Send verack", "Send verack after receiving peer version.", true, true},
    {"handshake.verack.recv", "cp1_handshake", "handshake", "Receive verack", "Wait for peer verack to complete handshake.", true, true},
    {"handshake.services", "cp1_handshake", "handshake", "Advertise NODE_NETWORK | NODE_WITNESS", "Set services flags required for full-node participation.", true, true},
    {"handshake.sendheaders", "cp1_handshake", "handshake", "Send sendheaders (BIP130)", "Announce preference for headers-first block propagation.", true, true},
    {"handshake.sendcmpct", "cp1_handshake", "handshake", "Send sendcmpct (BIP152)", "Negotiate compact block relay mode.", false, false},
    {"handshake.wtxidrelay", "cp1_handshake", "handshake", "Send wtxidrelay (BIP339)", "Announce witness tx relay support.", false, false},
    {"discovery.dns", "cp2_discovery", "discovery", "DNS seed resolution", "Resolve testnet4 DNS seeds to peer IP addresses.", true, true},
    {"discovery.manual_peers", "cp2_discovery", "discovery", "Manual peer list", "Connect via --peers / PEERS env (host:port list).", true, true},
    {"discovery.getaddr", "cp2_discovery", "discovery", "Send getaddr", "Request peer address gossip from connected peers.", true, true},
    {"discovery.addr.recv", "cp2_discovery", "discovery", "Receive and parse addr", "Deserialize addr message and store peer addresses.", true, true},
    {"discovery.addr.relay", "cp2_discovery", "discovery", "Relay addr to peers", "Forward known addresses to other connected peers.", false, false},
    {"discovery.multi_peer", "cp2_discovery", "discovery", "Multiple simultaneous outbound peers", "Maintain a pool of 3+ outbound connections.", true, true},
    {"headers.getheaders.send", "cp3_headers", "headers", "Send getheaders", "Request headers using block locator hashes.", true, true},
    {"headers.headers.recv", "cp3_headers", "headers", "Receive and parse headers", "Deserialize headers message (80-byte header + varint tx count).", true, true},
    {"headers.locator", "cp3_headers", "headers", "Block locator construction", "Build exponential block locator from stored header chain.", true, true},
    {"headers.persist", "cp3_headers", "headers", "Persist headers to RocksDB", "Store height, hash, prev_hash, timestamp for each header.", true, true},
    {"headers.genesis", "cp3_headers", "headers", "Genesis header seeded", "Height 0 genesis block stored as chain anchor.", true, true},
    {"headers.pow", "cp3_headers", "headers", "Proof-of-work validation", "Reject headers that do not meet nBits target.", true, true},
    {"headers.chain_link", "cp3_headers", "headers", "Chain link validation", "Reject headers whose prev_hash does not match stored tip.", true, true},
    {"headers.sync_to_tip", "cp3_headers", "headers", "Sync header chain to network tip", "Repeated getheaders until empty response or tip matches peer height.", true, true},
    {"headers.resume", "cp3_headers", "headers", "Resume header sync from RocksDB", "On restart, continue from stored best_height without re-fetching.", true, true},
    {"headers.inv_trigger", "cp3_headers", "headers", "inv(MSG_BLOCK) triggers getheaders", "On block inv, update locator and fetch new headers.", true, true},
    {"blocks.inv.recv", "cp4_blocks", "blocks", "Receive and parse inv", "Deserialize inv vectors (type + hash).", true, true},
    {"blocks.getdata.send", "cp4_blocks", "blocks", "Send getdata for blocks", "Request MSG_WITNESS_BLOCK via getdata.", true, true},
    {"blocks.block.recv", "cp4_blocks", "blocks", "Receive block message", "Read raw block payload from P2P wire.", true, true},
    {"blocks.block.store", "cp4_blocks", "blocks", "Store raw block bytes", "Write block to blocks/*.dat flat files.", true, true},
    {"blocks.notfound", "cp4_blocks", "blocks", "Handle notfound", "Request block from alternate peer on notfound.", true, true},
    {"blocks.parallel", "cp4_blocks", "blocks", "Parallel block download", "Fetch blocks from multiple peers concurrently.", false, false},
    {"tx.inv.recv", "cp5_tx_relay", "transactions", "Receive inv(MSG_WITNESS_TX)", "Parse transaction inventory announcements.", true, true},
    {"tx.getdata.send", "cp5_tx_relay", "transactions", "Send getdata for transactions", "Request tx bytes from peer.", true, true},
    {"tx.tx.recv", "cp5_tx_relay", "transactions", "Receive tx message", "Deserialize transaction from wire payload.", true, true},
    {"tx.mempool", "cp5_tx_relay", "transactions", "Send mempool (BIP35)", "Request peer mempool tx inv after connection.", true, true},
    {"tx.inv.send", "cp5_tx_relay", "transactions", "Announce transactions via inv", "Relay accepted mempool txs to peers.", true, true},
    {"tx.feefilter", "cp5_tx_relay", "transactions", "Send feefilter (BIP133)", "Advertise minimum fee rate for inv relay.", true, true},
    {"serve.getheaders", "cp6_serving", "serving", "Respond to getheaders", "Serve known headers to requesting peers.", true, true},
    {"serve.getdata.blocks", "cp6_serving", "serving", "Respond to getdata (blocks)", "Serve stored blocks to requesting peers.", true, false},
    {"serve.getdata.txs", "cp6_serving", "serving", "Respond to getdata (transactions)", "Serve mempool transactions to requesting peers.", true, false},
    {"serve.inv.blocks", "cp6_serving", "serving", "Announce new blocks via inv", "Broadcast block inv when tip advances.", true, false},
    {"keepalive.ping.recv", "cp7_keepalive", "keepalive", "Respond to ping with pong", "Reply to peer ping with matching nonce.", true, true},
    {"keepalive.ping.send", "cp7_keepalive", "keepalive", "Send periodic ping", "Probe idle connections with ping messages.", true, true},
    {"keepalive.timeout", "cp7_keepalive", "keepalive", "Disconnect stale peers", "Drop peers with no messages within timeout window.", true, true},
    {"ext.cmpctblock", "cp8_extensions", "extensions", "Receive cmpctblock (BIP152)", "Parse compact block messages.", false, true},
    {"ext.getblocktxn", "cp8_extensions", "extensions", "Send getblocktxn (BIP152)", "Request missing transactions for compact block.", false, false},
    {"ext.reject", "cp8_extensions", "extensions", "Send/receive reject", "Protocol-level reject messages for invalid payloads (inbound parse path implemented).", false, true},
    {"ext.bip324", "cp8_extensions", "extensions", "BIP324 v2 encrypted transport", "Encrypted P2P v2 transport instead of cleartext v1.", false, false},
};
} // namespace
