from __future__ import annotations

from collections.abc import Iterable
from typing import Protocol


class ChainstateStore(Protocol):
    """Native/Core operational state boundary for pybitnode."""

    def close(self) -> None: ...
    def get_meta(self, key: str, default: str | None = None) -> str | None: ...
    def set_meta(self, key: str, value: str) -> None: ...
    def get_sync_state(self, chain: str) -> dict | None: ...
    def upsert_sync_state(
        self,
        chain: str,
        *,
        best_height: int | None = None,
        best_hash: str | None = None,
        header_count: int | None = None,
        sync_status: str | None = None,
    ) -> None: ...
    def get_validated_height(self, chain: str = "testnet4") -> int: ...
    def get_validated_hash(self, chain: str = "testnet4") -> str | None: ...
    def set_validated_tip(self, height: int, block_hash_hex: str, *, chain: str = "testnet4") -> None: ...
    def record_header(
        self,
        height: int,
        block_hash: str,
        prev_hash: str,
        timestamp: int,
        *,
        header_serialized_hex: str | None = None,
    ) -> None: ...
    def get_header(self, height: int) -> dict | None: ...
    def get_header_hash(self, height: int) -> str | None: ...
    def max_header_height(self) -> int: ...
    def record_block(self, height: int, block_hash: str, file_name: str, file_offset: int, size: int) -> None: ...
    def get_block(self, height: int) -> dict | None: ...
    def max_stored_block_height(self) -> int: ...
    def get_utxo(self, txid: bytes, vout: int) -> dict | None: ...
    def add_utxo(self, txid: bytes, vout: int, *, height: int, value: int, script_pubkey: bytes, coinbase: bool) -> None: ...
    def add_utxos(self, utxos: Iterable[dict]) -> None: ...
    def spend_utxos(self, outpoints: Iterable[tuple[bytes, int]]) -> None: ...
    def replace_utxo_undo(self, chain: str, height: int, entries: list[dict]) -> None: ...
    def take_utxo_undo(self, chain: str, height: int) -> list[dict]: ...
    def summary(self, chain: str) -> dict: ...
